name: Manual Execute

on:
  workflow_dispatch:
    inputs:
      PARAMETER:
        required: true

jobs:
  manual-job:
    uses: ./.github/workflows/shared_process.yml
    with:
      PARAMETER: ${{ inputs.PARAMETER }}
